name: Build project with Maven
on:
  pull_request: 
  push: 
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:19.0.3-legacy
        env:
          KEYCLOAK_USER: keycloak
          KEYCLOAK_PASSWORD: keycloak1!
          DB_VENDOR: h2
        ports: [ 8443/tcp ]
        options: --health-cmd "curl -Iks https://localhost:8443" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Java setup
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: temurin
    - name: Cache
      uses: actions/cache@640a1c2554105b57832a23eea0b4672fc7a790d5 # pin@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      env:
        KEYCLOAK_URL: https://localhost:${{ job.services.keycloak.ports[8443] }}/auth
        KEYCLOAK_ENFORCE_SUBGROUPS_IN_GROUP_QUERY: false
      run: mvn -B clean install com.mycila:license-maven-plugin:check
