# If this workflow is triggered by a push to master, it
#        deploys a SNAPSHOT
# If this workflow is triggered by publishing a Release, it
#        deploys a RELEASE with the selected version
#        updates the project version by incrementing the patch version
#        commits the version update change to the repository's default branch.
# This workflow waits for the `build` workflow to complete successfully before proceeding.
name: Deploy artifacts with Maven
on:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@5a908a24814494009c4bb27c242ea38c93c593be # pin@v1.0.0
      id: wait-for-build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: build
        ref: ${{ env.GITHUB_SHA || github.ref }}
    - name: Cancel workflow when build fails
      if: steps.wait-for-build.outputs.conclusion == 'failure'
      run: echo "Build failed, skipping deploy" && exit 1
    - uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # pin@v2
    - name: Detect release type
      run: |-
        if [[ "${{github.ref}}" == "refs/heads/master" ]]; then
          echo "::set-output name=type::SNAPSHOT"
        else
          echo "::set-output name=type::RELEASE"
        fi
      id: release-detection
    - uses: actions/checkout@v5
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up Java environment
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
        gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE
    - name: Deploy SNAPSHOT / Release
      uses: camunda-community-hub/community-action-maven-release@v2
      with:
        release-version: ${{ github.event.release.tag_name }}
        release-profile: community-action-maven-release
        nexus-usr: ${{ secrets.NEXUS_USR }}
        nexus-psw: ${{ secrets.NEXUS_PSW }}
        sonatype-central-portal-usr: ${{ secrets.COMMUNITY_HUB_MAVEN_CENTRAL_CP_USR }}
        sonatype-central-portal-psw: ${{ secrets.COMMUNITY_HUB_MAVEN_CENTRAL_CP_PSW }}
        # maven-usr, maven-psw and maven-url are deprecated; they are required only for publishing to the legacy OSS Sonatype repository.
        # Once the io.zeebe namespace is migrated to the Sonatype Central Portal, these can be safely removed.
        maven-usr: ${{ secrets.COMMUNITY_HUB_MAVEN_CENTRAL_OSS_USR }}
        maven-psw: ${{ secrets.COMMUNITY_HUB_MAVEN_CENTRAL_OSS_PSW }}
        maven-url: oss.sonatype.org
        maven-gpg-passphrase: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
        maven-auto-release-after-close: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        maven-build-options: clean
      id: release
    - if: github.event.release
      name: Attach artifacts to GitHub Release (Release only)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.release.outputs.artifacts_archive_path }}
        asset_name: ${{ steps.release.outputs.artifacts_archive_path }}
        asset_content_type: application/zip
